### ISSUE TITLE
H5移动端的rem布局以及手淘flexible.js的使用

### ISSUE THREAD

**Issue by ximoThorn** [ximoThorn/ximoThorn.github.io#5]
# rem是什么
rem（font size of the root element）是指相对于根元素的字体大小的单位。简单的说它就是一个相对单位。看到rem大家一定会想起em单位，em（font size of the element）是指相对于父元素的字体大小的单位。它们之间其实很相似，只不过一个计算的规则是依赖根元素一个是依赖父元素计算。
# rem的实现
举个例子：
css代码：
```css
html {
   font-size:20px;
}
.btn {
   width: 6rem;
   height: 3rem;
   line-height: 3rem;
   font-size: 1.2rem;
   display: inline-block;
   background: #06c;
   color: #fff;
   border-radius: .5rem;
   text-decoration: none;
   text-align: center;
}
```

上面代码结果：

![_20180129163048](https://user-images.githubusercontent.com/32925631/35500562-d282b5c2-0511-11e8-836a-1a5ab4d7c87a.png)

然后我们再改变html的font-size的值，看看按钮发生上面变化:
```css
html {
   font-size:40px;
}
```
变化后：
![_20180129163422](https://user-images.githubusercontent.com/32925631/35500681-49a61a0e-0512-11e8-93be-c685776eb890.png)
我们只改变了html的font-size的值，.btn的width，height就变成了上面结果的两倍；
所以我们可以推算出：1rem的值就是html中font-size的值；html中font-size的改变就会导致按钮的大小发生改变，我们并不需要改变先前给按钮设置的宽度和高度，其实这就是我们最想看到的。
# rem的应用
虽然上面的例子很简单，但是在实际移动端的开发中，我们并不能去写死html的fons-size的值，因为移动端的屏幕宽度和分辨率的是不相同的，所以这才有了flexible的出现。
# flexible的简单介绍

是一个制作H5适配的开源库，可以[点击这里](https://github.com/amfe/lib-flexible/archive/master.zip)下载相关文件，获取需要的JavaScript和CSS文件

## 其实flexible就做了三件事

- 动态改写<meta>标签

- 给<html>元素添加data-dpr属性，并且动态改写data-dpr的值

- 给<html>元素添加font-size属性，并且动态改写font-size的值

## 把视觉稿中的px转换成rem

1. 首先，目前日常工作当中，视觉设计师给到前端开发人员手中的视觉稿尺寸一般是基于750px宽度为准；

2.  然后，flexible会将屏幕的宽度分成10份，即用10rem的值去对应视觉稿750px的宽度；

3.  最后，我们就可以计算1rem=75px，即我们所说的html中font-size的值就是75px，如果视觉稿的宽度为640px的话，那么1rem=64px，以此类推...

举个例子：
假入视觉稿的尺寸为750px，图中200px×150px的尺寸换算为rem的尺寸就是2.666667rem×2rem

## 快速计算

- 使用[sass](https://www.sass.hk/)的函数指令功能

```js
//设计图宽度 
//如设计稿750，分10份， 1rem = 75px
 $baseWidthRate: 75;   //如设计稿是750px的话，就是75
 
 // px转换为rem
@function r($num) {
    @return $num / $baseWidthRate + rem;
}
```

      这样我们就可以在scss文件中写：

```css
div {
   width: r(200);
   height: r(150);
}
```

- 使用Sublime Text3的话可以用[CSSREM](https://github.com/flashlizi/cssrem)插件快速生成rem

## flexible应用时产生的问题
大家都知道flexible.js引入时必须放在<head>最前面，但是在实际应用中可能我们在外部
引入时，页面在加载过程中可能会产生css错乱到齐整的排版闪烁问题，经思考后用一下方法解决

首先，在body标签加一个class名hide，hide代码如下：
 ```css
 .hide {
     display: none
 }  
```
然后，在flexible源码中大概90左右加上两行代码
```js
 if (doc.readyState === 'complete') {
      doc.body.style.fontSize = 12 * dpr + 'px';
      doc.body.className='';   //这是我们自己加上的
 } else {
      doc.addEventListener('DOMContentLoaded', function(e) {
          doc.body.style.fontSize = 12 * dpr + 'px';
          doc.body.className='';   //这是我们自己加上的
     }, false);
 }
```
原理大家都应该能看懂，不做解释

参考文章：[https://www.w3cplus.com/mobile/lib-flexible-for-html5-layout.html](https://www.w3cplus.com/mobile/lib-flexible-for-html5-layout.html)
